<a href="https://colab.research.google.com/github/NiharikaKomaragiri/Internship-Project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr1=np.array([1,2,3,4,5])
print('1-dim',arr1,sep='\n',end='\n\n')

arr2=np.array([[1,2,6],[3,4,5]])
print('2-dim',arr2,sep='\n',end='\n\n')

arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('multi-dim',arr3,sep='\n',end='\n\n')

1-dim
[1 2 3 4 5]

2-dim
[[1 2 6]
 [3 4 5]]

multi-dim
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



In [3]:
zeros=np.zeros((5,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
ones=np.ones((7,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
identity=np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
Full_array=np.full((5,3),True)
print(Full_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
Full_array=np.full((5,3),False)
print(Full_array)

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


In [15]:
range_arr=np.arange(3,21,3)
print(range_arr)

[ 3  6  9 12 15 18]


In [18]:
lin_space=np.linspace(0,200,5)
print(lin_space)

[  0.  50. 100. 150. 200.]
